### ISSUE TITLE
ImageFilterTest failures

### ISSUE THREAD

**Issue by marr** [hiromipaw/localpic#2]
```
$ bundle exec rake test test/workers/image_filter_test.rb
Run options: --seed 35424

# Running:

EE

Finished in 0.155864s, 12.8317 runs/s, 0.0000 assertions/s.

  1) Error:
ImageFilterTest#test_apply_filter_to_image:
NameError: uninitialized constant ServiceWorker::FileOperations
    app/workers/service_worker.rb:7:in `<class:ServiceWorker>'
    app/workers/service_worker.rb:4:in `<top (required)>'
    app/workers/image_filter.rb:1:in `<top (required)>'
    test/workers/image_filter_test.rb:7:in `block in <class:ImageFilterTest>'


  2) Error:
ImageFilterTest#test_image_filter_worker:
NameError: uninitialized constant ImageFilter::ImageOperations
    app/workers/image_filter.rb:2:in `<class:ImageFilter>'
    app/workers/image_filter.rb:1:in `<top (required)>'
    test/workers/image_filter_test.rb:7:in `block in <class:ImageFilterTest>'

2 runs, 0 assertions, 0 failures, 2 errors, 0 skips
```

**Comment by hiromipaw** [comment]
Do you have the concern defines?

**Comment by marr** [comment]
Yes, I have the `app/controllers/concerns/filters_operations.rb` file as this is a direct clone of the repo. Also I don't see an `ImageProcessing` class in the refile gem, was that supposed to be included as well?

**Comment by hiromipaw** [comment]
Ok so, I had included the ImageOperations lib with the idea that more filters could be defined, but let it open as an exercise.
I have now updated the repo with a few corrections. Please sync it and it should work.

File updated:

```
test/workers/image_filter_test.rb
config/application.rb
app/workers/image_filter.rb
```

Diff here: [cae9b9b](https://github.com/hiromipaw/localpic/commit/cae9b9b7c5aa756832fc326d07acd68bd1e9f23c)

**Comment by marr** [comment]
Thanks, that fixes the issue I was seeing!
